### PR TITLE
fix(tests): `files()` function of traverse workspace

### PR DESCRIPTION
**Pull request by max397574**

### CODE REVIEW

**Comment by max397574** [comment]
not sure if this actually fixes things
was hoping that the tests would run in the pr (I can't run the locally because of a weird bug)
the function is from here https://docs.rs/walkdir/latest/walkdir/#example-skip-hidden-files-and-directories-on-unix

**Comment by johanneshorner** [comment]
The hidden file is excluded correctly i think. But the WalkDir iterator also contains the directory it started from. So it's both visible files + "test/example_workspace".

**Comment by max397574** [comment]
thank you @johanneshorner that was the issue

**Comment by vhyrro** [comment]
Thanks! :purple_heart:

**Pull request merged**
